version: "3.9"
services:
  discovery:
    build: ../discovery-server
    ports:
      - "8761:8761"
    image: "discovery-service"
  matiere_B:
    build: ../Matiere-MicroS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3000:8080"
    image: "matiere-service"
  club_B:
    build: ../club
    environment:
     - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
     - "3001:8081"
    image: "club-service"
    depends_on:
     - event_A
  event_A:
      build: ../event
      environment:
       - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      ports:
       - "3002:8082"
      image: "event-service"
  etudiant_B:
    build: ../Etudiant-MicroS
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "3003:8083"
    image: "etudiant-service"